# Generated by Django 4.1.7 on 2023-03-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='equipo_local',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='partido',
            old_name='equipo_visitante',
            new_name='visitante',
        ),
        migrations.AddField(
            model_name='equipo',
            name='diferencia_goles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_a_favor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_en_contra',
            field=models.IntegerField(default=0),
        ),
    ]
