# Generated by Django 4.1.7 on 2023-03-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_rename_equipo_local_partido_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='goles',
            field=models.IntegerField(default=0),
        ),
    ]
