# Generated by Django 4.1.7 on 2023-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_jugador_goles'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('nombre', 'dorsal', 'equipo'), name='pk_jugador'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.UniqueConstraint(fields=('local', 'visitante'), name='unique_match'),
        ),
    ]
