# Generated by Django 4.1.7 on 2023-03-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_jugador_goles'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='league.equipo'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('nombre', 'dorsal', 'equipo'), name='pk_jugador'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.UniqueConstraint(fields=('local', 'visitante'), name='unique_match'),
        ),
    ]
