# Generated by Django 4.1.7 on 2023-03-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_jugador_pk_jugador_partido_unique_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='equipo',
            field=models.ForeignKey(default='SN', on_delete=django.db.models.deletion.CASCADE, to='league.equipo'),
        ),
    ]
