# Generated by Django 4.1.7 on 2023-03-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_tipoevento_alter_evento_tipo'),
        ('league', '0007_alter_evento_equipo'),
    ]

    operations = [
    ]
