# Generated by Django 4.1.7 on 2023-03-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_evento_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='diferencia_goles',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='goles_a_favor',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='goles_en_contra',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='ganador',
        ),
    ]
