# Generated by Django 4.1.7 on 2023-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_evento_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='diferencia_goles',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='goles_a_favor',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='goles_en_contra',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='liga',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='ganador',
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(to='league.jugador'),
        ),
        migrations.AddField(
            model_name='liga',
            name='equipos',
            field=models.ManyToManyField(to='league.equipo'),
        ),
    ]
