# Generated by Django 4.1.7 on 2023-04-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_remove_jugador_pk_jugador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='local',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partido',
            name='visitante',
            field=models.CharField(max_length=50),
        ),
    ]
