# Generated by Django 4.1.7 on 2023-04-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_alter_partido_local_alter_partido_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='league.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='league.equipo'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('nombre', 'dorsal', 'equipo'), name='pk_jugador'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.UniqueConstraint(fields=('local', 'visitante'), name='unique_match'),
        ),
    ]
