# Generated by Django 4.1.7 on 2023-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_alter_partido_local_alter_partido_visitante_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jugador',
            name='pk_jugador',
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('nombre', 'dorsal'), name='pk_jugador'),
        ),
    ]
