# Generated by Django 4.1.7 on 2023-04-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_remove_jugador_pk_jugador_jugador_pk_jugador'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partido',
            name='unique_match',
        ),
    ]
