# Generated by Django 3.2 on 2023-03-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEquip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cognoms', models.CharField(max_length=70)),
                ('gol', models.IntegerField()),
                ('targetaGroga', models.IntegerField()),
                ('targetaVermella', models.IntegerField()),
                ('asistencies', models.IntegerField()),
                ('faltes', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lliga', models.CharField(max_length=50)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laLliga.equip')),
            ],
        ),
        migrations.CreateModel(
            name='Partit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('golVisitant', models.IntegerField()),
                ('golLocal', models.IntegerField()),
                ('lliga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laLliga.lliga')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='laLliga.equip')),
                ('visitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitant', to='laLliga.equip')),
            ],
        ),
        migrations.AddField(
            model_name='equip',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laLliga.jugador'),
        ),
        migrations.CreateModel(
            name='Classificacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicio', models.IntegerField()),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laLliga.equip')),
                ('lliga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laLliga.lliga')),
            ],
        ),
    ]
