# Generated by Django 3.2 on 2023-03-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laLliga', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classificacio',
            new_name='Classificacion',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='faltes',
            new_name='faltesComeses',
        ),
        migrations.AddField(
            model_name='jugador',
            name='faltesRebudes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
