# Generated by Django 3.2 on 2023-03-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laLliga', '0002_auto_20230310_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.TimeField()),
                ('tipus_event', models.CharField(choices=[('GOL', 'Gol'), ('AUTOGOL', 'Autogol'), ('FALTA', 'Falta'), ('PENALTI', 'Penalty'), ('MANS', 'Mans'), ('CESSIO', 'Cessio'), ('FORA_DE_JOC', 'Fora De Joc'), ('ASSISTENCIA', 'Assistencia'), ('TARGETA_GROGA', 'Targeta Groga'), ('TARGETA_VERMELLA', 'Targeta Vermella')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='equip',
            old_name='nomEquip',
            new_name='nom_equip',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='nom',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='faltesComeses',
            new_name='dorsal',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='faltesRebudes',
            new_name='gols',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='gol',
            new_name='targeta_groga',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='numero',
            new_name='targeta_vermella',
        ),
        migrations.RenameField(
            model_name='lliga',
            old_name='lliga',
            new_name='nom_lliga',
        ),
        migrations.RenameField(
            model_name='partit',
            old_name='data',
            new_name='data_partit',
        ),
        migrations.RenameField(
            model_name='partit',
            old_name='local',
            new_name='equip_local',
        ),
        migrations.RenameField(
            model_name='partit',
            old_name='visitant',
            new_name='equip_visitant',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='cognoms',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='targetaGroga',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='targetaVermella',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='golLocal',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='golVisitant',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='hora',
        ),
        migrations.AddField(
            model_name='jugador',
            name='cognnoms_jugador',
            field=models.CharField(default='XXX', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='nom_jugador',
            field=models.CharField(default='YYY', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lliga',
            name='classificacio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lliga',
            name='temporada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lliga',
            name='equip',
        ),
        migrations.AddField(
            model_name='lliga',
            name='equip',
            field=models.ManyToManyField(to='laLliga.Equip'),
        ),
        migrations.DeleteModel(
            name='Classificacion',
        ),
        migrations.AddField(
            model_name='event',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laLliga.equip'),
        ),
        migrations.AddField(
            model_name='event',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laLliga.jugador'),
        ),
        migrations.AddField(
            model_name='event',
            name='partit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laLliga.partit'),
        ),
    ]
