# Generated by Django 3.2 on 2023-03-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laLliga', '0003_auto_20230324_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lliga',
            name='classificacio',
        ),
    ]
