# Generated by Django 3.2 on 2023-03-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laLliga', '0004_remove_lliga_classificacio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='jugador',
        ),
        migrations.AddField(
            model_name='equip',
            name='jugador',
            field=models.ManyToManyField(to='laLliga.Jugador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='alias',
            field=models.CharField(max_length=200),
        ),
    ]
