# Generated by Django 3.2 on 2023-03-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laLliga', '0005_auto_20230324_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lliga',
            name='temporada',
        ),
    ]
