# Generated by Django 3.2 on 2023-03-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laLliga', '0006_remove_lliga_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='lliga',
            name='temporada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='asistencies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='dorsal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='gols',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='targeta_groga',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='targeta_vermella',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partit',
            name='data_partit',
            field=models.DateField(null=True),
        ),
    ]
