# Generated by Django 3.2 on 2023-03-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laLliga', '0007_auto_20230324_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lliga',
            old_name='equip',
            new_name='equips',
        ),
    ]
