# Generated by Django 3.2 on 2023-03-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laLliga', '0008_rename_equip_lliga_equips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tipus_event',
            new_name='tipus',
        ),
    ]
