# Generated by Django 3.2 on 2023-03-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laLliga', '0009_rename_tipus_event_event_tipus'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detalls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='jugador2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_rebuts', to='laLliga.jugador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='laLliga.jugador'),
        ),
    ]
